apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: teamcity
  labels:
    app: teamcity
spec:
  template:
    metadata:
      labels:
        app: teamcity
        tier: web
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: teamcity-disk
      containers:
        - name: teamcity
          image: jetbrains/teamcity-server:2020.1.4
          imagePullPolicy: Always
          ports:
            - containerPort: 8111
          volumeMounts:
            - name: data
              mountPath: /data/teamcity_server/datadir
---
apiVersion: v1
kind: Service
metadata:
  name: teamcity
  labels:
    app: teamcity
spec:
  type: NodePort
  selector:
    app: teamcity
    tier: web
  ports:
    - port: 8111
      targetPort: 8111
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: teamcity-agent
  labels:
    app: teamcity-agent
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: teamcity-agent
        tier: web
    spec:
      containers:
        - name: teamcity-agent
          securityContext:
            privileged: true
          env:
            - name: SERVER_URL
              value: http://teamcity:8111
            - name: DOCKER_IN_DOCKER
              value: start
            - name: AGENT_NAME
              value: agent
          image: khainx127/teamcity-agent
          imagePullPolicy: Always
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: teamcity-db
  labels:
    app: teamcity-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: teamcity-db
        tier: web
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: teamcity-db-disk
      containers:
        - name: teamcity-db
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_USER
              value: teamcity
            - name: MYSQL_DATABASE
              value: teamcity
          image: mysql:8.0
          imagePullPolicy: Always
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: teamcity-db
  labels:
    app: teamcity-db
spec:
  type: NodePort
  selector:
    app: teamcity-db
    tier: web
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-disk
spec:
  # storageClassName: ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-db-disk
spec:
  # storageClassName: ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi